version: '3.8'
services:
  web:
    build: 
      dockerfile: Dockerfile
      context: .
      tags:
        - polls:latest
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app